"""Milestone 2 — `probe-proxy verify <config-file>`: hand-edit counter.

Re-runs the replay suite against a user's EXISTING Caddyfile and reports:
  (a) drift — how far the managed block has drifted from the originally
      generated config (marker hash mismatch -> normalized-body diff),
  (b) broken probes — replay diffs vs a fresh direct probe run.

Drift + broken-probe counts go into the report (and probe_results.db) —
this is the instrumentation that makes "users still hand-edit" measurable.
"""
from __future__ import annotations

import difflib
import json
import re
import sys
from pathlib import Path

import docker

from . import cli, probes, synthesize
from .replay import (confirm_diffs, diff_fingerprints, free_port,
                     start_caddy, wait_caddy, wait_ready)

MARKER_RE = re.compile(r"^# managed-by probe-proxy .* sha256:([0-9a-f]+)",
                       re.MULTILINE)


def extract_block(text: str):
    """Return (marker_hash_or_None, block_text) from a user Caddyfile.

    The managed block is the marker line plus everything after it up to
    the end of file (or the next non-managed line block boundary — we
    simply take the whole trailing config; users normally paste the
    block at the end of their Caddyfile).
    """
    m = MARKER_RE.search(text)
    if not m:
        return None, text
    after = text[m.end():]
    return m.group(1), after.strip()


def block_hash(body: str) -> str:
    import hashlib
    return hashlib.sha256(body.strip().encode()).hexdigest()[:16]


def drift_report(original_hash: str, current_body: str) -> dict:
    """Compare current managed block body vs its recorded hash.

    Drift is measured as a normalized edit: we can't recover the original
    text from a hash, so drift = marker-hash matches current body?
    (no drift) : (hash mismatch -> we diff normalized bodies line-sets).
    """
    current_hash = block_hash(current_body)
    if original_hash == current_hash:
        return {"hash_matches": True, "edited": False, "added_lines": [],
                "removed_lines": [], "edit_count": 0}
    # We do not have the original body — report unidiff of the marker
    # claim vs reality by listing which lines are non-Caddy-default.
    # Minimum viable: edited=True + the number of lines in the block.
    return {"hash_matches": False, "edited": True,
            "edit_count": None,
            "note": ("marker hash no longer matches the block body; "
                     "the block has been hand-edited (or reformatted)")}


def main(config_path: str, as_json: bool = False):
    path = Path(config_path)
    if not path.exists():
        raise SystemExit(f"error: config file '{config_path}' not found")
    text = path.read_text()
    original_hash, body = extract_block(text)

    if original_hash is None:
        msg = ("error: no '# managed-by probe-proxy' marker in this config.\n"
               "verify works on configs generated by probe-proxy (the "
               "marker carries the original block's hash).")
        if as_json:
            print(json.dumps({"error": "no-marker"}, indent=2))
        else:
            print(msg, file=sys.stderr)
        return 1

    # figure out the upstream from the config body
    m = re.search(r"reverse_proxy\s+(\S+)", body)
    if not m:
        print("error: cannot find reverse_proxy upstream in config",
              file=sys.stderr)
        return 1
    upstream = m.group(1)

    # resolve a direct route to the app (docker container name or host:port)
    dc = docker.from_env()
    target = upstream.split(":")[0]
    cont = None
    host_port = None
    try:
        cont = dc.containers.get(target)
    except docker.errors.NotFound:
        for c in dc.containers.list():
            labels = c.labels or {}
            svc = labels.get("com.docker.compose.service", "")
            proj = labels.get("com.docker.compose.project", "")
            if svc and (svc == target or f"{proj}-{svc}" == target):
                cont = c
                break
    if cont is not None:
        for p, binds in (cont.attrs["NetworkSettings"]["Ports"] or {}).items():
            if binds and binds[0].get("HostPort"):
                host_port = int(binds[0]["HostPort"])
                break
    if host_port is None or cont is None:
        print(f"error: cannot reach upstream '{target}' — is its container "
              f"running with a published port?", file=sys.stderr)
        return 1

    direct_base = f"http://127.0.0.1:{host_port}"
    print(f"[*] probing app directly at {direct_base}", file=sys.stderr)
    direct = probes.run_all(direct_base)

    # run user's config through Caddy on a dedicated network attached to
    # the app (container-name DNS needs a user-defined network)
    import uuid
    net = dc.networks.create(f"probe-proxy-verify-{uuid.uuid4().hex[:6]}",
                             driver="bridge")
    try:
        net.connect(cont.id)
    except Exception as e:
        print(f"error: cannot attach app to probe network: {e}",
              file=sys.stderr)
        return 1

    caddy = None
    try:
        caddy, cport = start_caddy(dc, net.name, text)
        wait_caddy(cport)
        print(f"[*] replaying probe suite through your config "
              f"(127.0.0.1:{cport})", file=sys.stderr)
        via = probes.run_all(f"http://127.0.0.1:{cport}")
        diffs = diff_fingerprints(direct, via)
        if diffs:
            diffs = confirm_diffs(direct_base, f"http://127.0.0.1:{cport}", diffs)
    finally:
        if caddy:
            try:
                caddy.stop(timeout=3)
            except Exception:
                pass
        try:
            net.disconnect(cont.id)
        except Exception:
            pass
        try:
            net.remove()
        except Exception:
            pass

    drift = drift_report(original_hash, body)

    # record in the hand-edit counter store
    cli.count_hand_edit(str(path), 1 if drift["edited"] else 0)

    if as_json:
        print(json.dumps({"config": str(path), "upstream": upstream,
                          "drift": drift, "broken_probes": diffs,
                          "n_broken": len(diffs)}, indent=2, default=str))
    else:
        edited = "YES — block drifted from generated config" \
            if drift["edited"] else "no (hash matches)"
        print(f"\n=== verify report for {path} ===")
        print(f"upstream:      {upstream}")
        print(f"hand-edited:   {edited}")
        print(f"broken probes: {len(diffs)}")
        for d in diffs:
            print(f"  {d['probe']}.{d['key']}: direct={str(d['direct'])[:40]} "
                  f"via-your-config={str(d['via'])[:40]}")
        if drift["edited"] and not diffs:
            print("\nverdict: edited but still behavior-preserving "
                  "(drift without damage).")
        elif drift["edited"] and diffs:
            print("\nverdict: edits BROKE probe behavior — see above.")
        elif not drift["edited"] and not diffs:
            print("\nverdict: unchanged and verified.")
        else:
            print("\nverdict: unedited but environment changed (probes "
                  "now diff) — app behavior drifted, not the config.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "Caddyfile"))
